---
# action.yml
#
name: logToCheckStyle
description: Convert text log to CheckStyle xml format
inputs:
  in:
    description: Source log path (Textual input log)
    required: true
  out:
    description: Target log path (CheckStyle xml format log)
    required: true
  root:
    description: Prefix to remove from paths in log
    required: false
    default:
  annotate:
    description: Turn annotation off/on (will default = true in github workflow in future)
    required: false
    default: false  # Turning off by default for now
# outputs:
#  outpath:  # id of output
#    description: The output path
runs:
  using: composite
  steps:
    - name: Analyse logfile
      shell: ${{ runner.os == 'Windows' && 'bash' || 'sh' }}
      run: |
        echo ::group::Analyze log file
        python -m pip install regex
        '${{ github.action_path }}/entrypoint.sh' '${{ inputs.in }}' '${{ inputs.out }}' '${{ inputs.root }}', '${{ inputs.annotate }}'
        echo ::endgroup::
